name: Copy file from protos to services

on:
  push:
    branches:
      - main
    paths:
      - 'protos/**'

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy .proto files to services
      run: |
        services=("user")

        for service in "${services[@]}"; do
          cp ./protos/*.proto ./$service/protos/
        done
